"""
build_report.py — assemble results/REPORT.md from sweep outputs, autointerp
results, UMAP figures, and cluster meta-autointerp.

Reads:
  - results/figures/*.png         (from build_steering_figures.py + run_umap.py)
  - results/targeted_steering/<model>/k*_a*.jsonl
  - results/autointerp_local/<model>/feat_*.json
  - results/clusters/cluster_meta.json
  - data/rankings/<model>.csv

Writes:
  - results/REPORT.md
"""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

from build_steering_figures import aggregate_model_dir


SECTIONS = """\
1. Headline finding
2. Setup recap
3. Targeted-steering sweep
4. Decoder geometry
5. A-excl autointerp summary
6. Discussion
7. Open questions
"""


def fmt_best(model_short: str, rows: list[dict]) -> str:
    if not rows:
        return f"- **{model_short}** — no rows."
    best = max(rows, key=lambda r: r["d_steered_clean_tool"])
    return (
        f"- **{model_short}** — best Δ A tool-corr. vs clean: "
        f"**{best['d_steered_clean_tool']:+.2f}%** at "
        f"k%={best['k_pct']:g}, α={best['alpha']:g} "
        f"(steered={best['steered_tool_pct']:.1f}%, clean={best['clean_tool_pct']:.1f}%, "
        f"recon={best['recon_tool_pct']:.1f}%, n={best['n']})"
    )


def collect_top_features(
    autointerp_dir: Path,
    rankings_csv: Path,
    n: int = 20,
) -> list[dict]:
    """Top-N A-excl features by cohens_d, joined with their explanations."""
    if not rankings_csv.exists():
        return []
    rows = list(csv.DictReader(rankings_csv.open()))
    rows = [r for r in rows if r.get("sign", "tool") == "tool"]
    rows.sort(key=lambda r: float(r["cohens_d"]), reverse=True)

    explanations: dict[int, dict] = {}
    if autointerp_dir.exists():
        for sub in autointerp_dir.iterdir():
            if not sub.is_dir():
                continue
            for fp in sub.glob("feat_*.json"):
                try:
                    data = json.loads(fp.read_text())
                except json.JSONDecodeError:
                    continue
                idx = int(data.get("feat_idx", -1))
                if idx >= 0:
                    explanations[idx] = data

    out = []
    for r in rows[:n]:
        idx = int(r["feature_idx"])
        e = explanations.get(idx, {})
        out.append({
            "feature_idx": idx,
            "cohens_d": float(r["cohens_d"]),
            "auroc": float(r["auroc"]),
            "fire_rate_tool": float(r["fire_rate_tool"]),
            "explanation": e.get("explanation", "(not autointerp'd yet)"),
            "detection_score": e.get("detection_score", -1.0),
        })
    return out


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--steering-root", type=Path, default=Path("results/targeted_steering"))
    p.add_argument("--autointerp-root", type=Path, default=Path("results/autointerp_local"))
    p.add_argument("--rankings-dir", type=Path, default=Path("data/rankings"))
    p.add_argument("--clusters-meta", type=Path, default=Path("results/clusters/cluster_meta.json"))
    p.add_argument("--figures-dir", type=Path, default=Path("results/figures"))
    p.add_argument("--out", type=Path, default=Path("results/REPORT.md"))
    p.add_argument("--main-model", default="dfc-D8k-excl10-freeexcl-k160")
    args = p.parse_args()

    args.out.parent.mkdir(parents=True, exist_ok=True)
    md_lines: list[str] = []

    # ── Header ────────────────────────────────────────────────────────────
    md_lines.append("# Targeted-Neuron Steering, Local-Gemma Autointerp, and Decoder UMAP")
    md_lines.append("")
    md_lines.append("Generated by `build_report.py`. See "
                    "`docs/superpowers/specs/2026-04-25-targeted-steering-and-autointerp-design.md` "
                    "for hypotheses and methodology.")
    md_lines.append("")

    # ── 1. Headline + best-cell summary ───────────────────────────────────
    md_lines.append("## 1. Headline finding")
    md_lines.append("")
    if (args.figures_dir / "compare_models_best_cell.png").exists():
        md_lines.append("![best-cell-per-model](figures/compare_models_best_cell.png)")
        md_lines.append("")

    if args.steering_root.exists():
        for md in sorted(args.steering_root.iterdir()):
            if md.is_dir():
                rows = aggregate_model_dir(md)
                md_lines.append(fmt_best(md.name, rows))
        md_lines.append("")

    # ── 2. Setup recap ────────────────────────────────────────────────────
    md_lines.append("## 2. Setup recap")
    md_lines.append("")
    md_lines.append(
        "Sweep targets **Model A (ToolRL-Qwen2.5-3B)** with post-top-k delta "
        "steering on the top-k% most-discriminative A-exclusive features "
        "(ranked by Cohen's d on tool vs FineWeb activations). Evaluation: "
        "100 ToolRL hold-out prompts; rubric per `score_response`. Three "
        "scores per prompt: `clean` (no patch), `recon` (full crosscoder "
        "decode of Model A patched), `steered` (h_a + delta).")
    md_lines.append("")
    md_lines.append(
        f"Sweep grid: k% ∈ {{1, 2, 4, 8, 16, 32, 64, 100}} × "
        f"α ∈ {{0, 1, 6, 16, 32, 64}}. Models: 3 from "
        f"`analysis/model_selection_recommendation.md`.")
    md_lines.append("")

    # ── 3. Steering sweep figures ─────────────────────────────────────────
    md_lines.append("## 3. Targeted-steering sweep")
    md_lines.append("")
    if args.steering_root.exists():
        for md in sorted(args.steering_root.iterdir()):
            if not md.is_dir():
                continue
            short = md.name
            md_lines.append(f"### {short}")
            md_lines.append("")
            for tag in [
                ("dA_tool_vs_clean",    "Δ Model-A tool-correctness vs clean"),
                ("dA_tool_vs_recon",    "Δ Model-A tool-correctness vs full-recon"),
                ("dA_overall_vs_clean", "Δ Model-A overall_score vs clean"),
            ]:
                fig = args.figures_dir / f"heatmap_{short}_{tag[0]}.png"
                if fig.exists():
                    md_lines.append(f"![{tag[1]}](figures/{fig.name})")
                    md_lines.append("")
            for fname in [
                f"lineplot_{short}_dA_vs_kpct.png",
                f"lineplot_{short}_dA_vs_alpha.png",
            ]:
                if (args.figures_dir / fname).exists():
                    md_lines.append(f"![{fname}](figures/{fname})")
                    md_lines.append("")

    # ── 4. Decoder geometry ──────────────────────────────────────────────
    md_lines.append("## 4. Decoder geometry (UMAP)")
    md_lines.append("")
    for fname in ["umap_partitions.png", "umap_aexcl_clusters.png",
                  "umap_aexcl_clusters_labeled.png"]:
        if (args.figures_dir / fname).exists():
            md_lines.append(f"![{fname}](figures/{fname})")
            md_lines.append("")

    if args.clusters_meta.exists():
        meta = json.loads(args.clusters_meta.read_text())
        md_lines.append("### Cluster names (Gemma meta-autointerp)")
        md_lines.append("")
        md_lines.append("| Cluster | Members | Name | Summary |")
        md_lines.append("|--------:|--------:|------|---------|")
        for cid, m in sorted(meta.items(), key=lambda kv: int(kv[0])):
            md_lines.append(
                f"| {cid} | {m.get('n_members', 0)} | "
                f"{m.get('name', '')} | {m.get('summary', '')} |"
            )
        md_lines.append("")

    # ── 5. A-excl autointerp summary ──────────────────────────────────────
    md_lines.append(f"## 5. A-excl autointerp summary — top 20 ({args.main_model})")
    md_lines.append("")
    feats = collect_top_features(
        args.autointerp_root / args.main_model,
        args.rankings_dir / f"{args.main_model}.csv",
        n=20,
    )
    if feats:
        md_lines.append("| feat | cohens_d | auroc | fire_rate_tool | det_score | explanation |")
        md_lines.append("|-----:|---------:|------:|---------------:|----------:|-------------|")
        for f in feats:
            md_lines.append(
                f"| {f['feature_idx']} | {f['cohens_d']:+.3f} | "
                f"{f['auroc']:.3f} | {f['fire_rate_tool']:.3f} | "
                f"{f['detection_score']:.3f} | {f['explanation']} |"
            )
        md_lines.append("")
    else:
        md_lines.append("(autointerp results not present yet — run `run_autointerp_local.py`)")
        md_lines.append("")

    # ── 6. Discussion + 7. open questions ────────────────────────────────
    md_lines.append("## 6. Discussion")
    md_lines.append("")
    md_lines.append(
        "- H1 (steering improvement) — see best-cell numbers above. "
        "Compare against the paper's Δ_A ≈ +30 pp post-recon mean "
        "(`results/results_full (1).jsonl`).")
    md_lines.append(
        "- H2 (non-monotone in k%) — inspect `lineplot_*_dA_vs_kpct.png` "
        "per model.")
    md_lines.append(
        "- H3 (cluster interpretability) — see Section 4 cluster table.")
    md_lines.append("")
    md_lines.append("## 7. Open questions")
    md_lines.append("")
    md_lines.append(
        "RL hesitation / stubbornness probe design lives in "
        "`docs/rl_boundaries.md` (no code yet).")

    args.out.write_text("\n".join(md_lines) + "\n")
    print(f"[report] wrote {args.out}")


if __name__ == "__main__":
    main()
